#!/bin/sh
echo "Running libtoolize..."
libtoolize
echo "Running aclocal..."
aclocal
echo "Running automake..."
automake --add-missing 
echo "Running autoconf..."
autoconf -f 
echo "Compiling java sources..."
if ! which mvn 2>&1 > /dev/null
then
    echo "Maven not found: install it!"
    exit 1
fi
(cd swift-jvm; mvn package)
echo "Turbine JVM Engine: bootstrap: OK"
exit 0
